name: Auto Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  auto-release:
    uses: apple/swift-temporal-sdk/.github/workflows/auto-release.yml@ffeb89de74c4a1296bb6ee5cfc880a78bd7c3ac4 # main as of 2026-09-18
